name: Deploy Quarto Site to GitHub Pages
permissions: 
    contents: write
    pages: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'  # Specify the R version you need

      - name: Install required R packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          
      - name: Render Quarto site
        run: |
          quarto render --to html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site  # Path to the rendered Quarto site
          destination_dir: .       # Publish to the root of the gh-pages branch
